name: Feishu Table Processing
on:
  repository_dispatch:  # 接收仓库调度事件（飞书HTTP触发）
    types: [feishu_QSA_trigger]  # 自定义事件类型

jobs:
  process-feishu-table:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # 适配Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lark-oapi requests pandas openpyxl pyexcel  # 安装脚本依赖

      - name: Run Feishu table script
        env:
          # 敏感信息通过GitHub Secrets传递
          APP_ID: ${{ secrets.FEISHU_APP_ID }}
          APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          TARGET_TABLE_ID: ${{ secrets.TARGET_TABLE_ID }}

          # 从触发事件中读取动态参数（优先repository_dispatch的client_payload，其次workflow_dispatch的inputs）
          DWBG_TOKEN: ${{ github.event.client_payload.DWBG_TOKEN || github.event.inputs.DWBG_TOKEN }}
          DWBG_TABLE_ID: ${{ github.event.client_payload.DWBG_TABLE_ID || github.event.inputs.DWBG_TABLE_ID }}
          ROW_ID: ${{ github.event.client_payload.ROW_ID || github.event.inputs.ROW_ID }}
          
        run: python feishu_QSA_script.py  # 执行改造后的脚本
